theme: minima
title: Kaixo!
author: Alazne Aldayturriaga
email: tu-nombre@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Nire webgunera oso polita gelditu da

# social links
twitter_username: tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  tu-usuario-github # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
