theme: minima
title: Portafolio de Alazne Aldayturriaga
author: Alazne Aldayturriaga
email: alaznealdarri@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Kaixo! Hau da nire repositorioa. Espero dut hemen partekatzen dudana gustatzea.

# social links
twitter_username: alaznealdaytu # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  alaznealdayturriaga # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: false # cámbialo a false para eliminar los extractos de la página principal
